"""
🎙️ Audio Podcast Generator - Week 1: n8n Fundamental
======================================================
สร้างไฟล์เสียงบรรยาย (Podcast) พร้อมเสียง AI ภาษาไทย
เนื้อหาจาก lecture.tex (27 slides) - รวมเป็นไฟล์เดียว

Setup:
    pip install edge-tts

Usage:
    python audio_generator_lab01.py
"""

import asyncio
import edge_tts
from pathlib import Path

# ============================================
# CONFIGURATION
# ============================================
OUTPUT_FILE = "week01-n8n-fundamental-podcast.mp3"

# เสียงไทย
VOICE = "th-TH-NiwatNeural"
# VOICE = "th-TH-PremwadeeNeural"  # เสียงผู้หญิง

# ลดความเร็วลง 15% เพื่อความชัดเจน
RATE = "-15%"

# ============================================
# SCRIPT - Week 1: n8n Fundamental
# รวมทุก slide เป็น script เดียว (27 slides)
# ============================================
SCRIPT = """
สวัสดีครับนักศึกษาทุกคน...
ยินดีต้อนรับเข้าสู่ Week 1... เรื่อง n8n Fundamental ครับ...
วันนี้เราจะมาเรียนรู้เกี่ยวกับ Introduction to Workflow Automation...
และทำความรู้จักกับ n8n ซึ่งเป็นเครื่องมือที่เราจะใช้ตลอดคอร์สนี้...
พร้อมกันหรือยังครับ?... ไปเริ่มกันเลย!...

มาดูสารบัญกันก่อนนะครับ...
วันนี้เราจะเรียน 5 หัวข้อหลักๆ...
หัวข้อแรก... Introduction to Workflow Automation...
หัวข้อที่สอง... n8n Overview...
หัวข้อที่สาม... Core Concepts...
หัวข้อที่สี่... Essential Nodes...
และหัวข้อสุดท้าย... Hands-on Demo...
พร้อมแล้วก็ไปกันเลยครับ!...

มาเริ่มกันที่หัวข้อแรกครับ... Workflow Automation คืออะไร?...
Workflow Automation คือ การทำให้งานที่ทำซ้ำๆ ทำงานอัตโนมัติ...
ลองเปรียบเทียบดูนะครับ...
ก่อน Automation... เราต้องทำงานซ้ำๆ ด้วยมือ... เสียเวลามาก...
มีโอกาสผิดพลาดสูง... และต้องใช้คนตลอดเวลา...
แต่หลัง Automation... ระบบทำงานอัตโนมัติ... ประหยัดเวลา...
ลดข้อผิดพลาด... และทำงานได้ตลอด 24 ชั่วโมง 7 วันครับ...

ทำไมเราต้อง Automate ครับ?...
มาดูประโยชน์ของ Workflow Automation กันนะครับ...
หนึ่ง... ประหยัดเวลา... ลดงาน manual ที่ทำซ้ำๆ...
สอง... ลดข้อผิดพลาด... ระบบทำงานตาม logic ที่กำหนด...
สาม... เพิ่มประสิทธิภาพ... ทำงานได้เร็วขึ้น...
สี่... Scalable... รองรับงานจำนวนมากได้...
และห้า... ติดตามได้... มี log และ history ครับ...

มาดูตัวอย่างการใช้งาน Workflow Automation กันครับ...
ในฝั่ง Business... เราสามารถใช้...
ส่ง Email อัตโนมัติ... แจ้งเตือนใน Slack หรือ Line...
สร้าง Report อัตโนมัติ... Sync ข้อมูลระหว่างระบบ...
ส่วนในฝั่ง Development... เราใช้ได้กับ...
CI/CD Pipeline... API Integration...
Data Processing... และ Monitoring แอนด์ Alerting ครับ...

มาเปรียบเทียบ Workflow Automation Tools กันครับ...
เรามี n8n, Zapier, และ Make...
n8n เป็น Open Source... Self-hosted ได้...
Free Tier ไม่จำกัด... และมี Code Node ที่ทรงพลัง...
ส่วน Zapier และ Make ไม่ใช่ Open Source...
ไม่สามารถ Self-hosted ได้... และ Free Tier มีข้อจำกัด...
สรุปคือ n8n เท่ากับ Open Source บวก Self-hosted บวก Free บวก Powerful ครับ...

ทำไมเราถึงเลือก n8n ครับ?...
หนึ่ง... Open Source... ฟรี และดู source code ได้...
สอง... Self-hosted... ติดตั้งบน server ตัวเอง ควบคุมข้อมูลได้...
สาม... No Vendor Lock-in... ไม่ผูกติดกับ provider...
สี่... มากกว่า 400 Integrations... เชื่อมต่อได้หลายบริการ...
ห้า... Code Node... เขียน JavaScript ได้เต็มที่...
และหก... Active Community... มีคนใช้และพัฒนาต่อเนื่องครับ...

มาถึงหัวข้อที่สอง... n8n Overview ครับ...
n8n อ่านว่า โนดเมชัน หรือ nodemation...
เป็น Workflow Automation Tool...
สร้างโดย Jan Oberhauser ในปี 2019...
เขียนด้วย TypeScript...
License เป็นแบบ Fair-code หรือ Source Available...
และมี GitHub Stars มากกว่า 40,000 ครับ...
n8n ย่อมาจาก node-based automation ครับ...

มาดูสถาปัตยกรรมของ n8n กันครับ...
หลักการทำงานคือ... มี Trigger Node... ส่งข้อมูล JSON ไปยัง Process Node...
แล้ว Process Node ก็ส่งต่อไปยัง Action Node...
หลักการสำคัญคือ...
Node-based... แต่ละ Node ทำหน้าที่เฉพาะ...
Visual Editor... ลากวาง เชื่อมต่อ Node ได้ง่าย...
และ Data Flow... ข้อมูลไหลผ่าน Node เป็น JSON ครับ...

มาดูวิธีติดตั้ง n8n กันครับ...
วิธีที่ 1 ใช้ Docker ซึ่งเป็นวิธีที่แนะนำ...
รันคำสั่ง docker run แล้วกำหนด port 5678...
วิธีที่ 2 ใช้ npm...
รันคำสั่ง npm install n8n -g...
แล้วก็รัน n8n start...
หลังจากติดตั้งเสร็จ เปิดใช้งานที่ URL localhost port 5678 ครับ...

มาดู n8n Interface กันครับ...
ส่วนประกอบหลักมี 5 ส่วน...
หนึ่ง... Canvas... พื้นที่สร้าง Workflow อยู่ตรงกลาง...
สอง... Node Panel... รายการ Node ทั้งหมดอยู่ทางซ้าย...
สาม... Execution Panel... ดูผลการทำงานอยู่ทางขวา...
สี่... Top Menu... มีปุ่ม Save, Execute, Settings...
และห้า... Sidebar... มี Workflows, Credentials, Variables ครับ...

มาถึงหัวข้อที่สาม... Core Concepts ครับ...
Workflow คืออะไร?...
Workflow คือ ชุดของ Node ที่เชื่อมต่อกันเพื่อทำงานอัตโนมัติ...
ตัวอย่างเช่น... Webhook Node ต่อไปยัง Code Node...
แล้ว Code Node ก็ต่อไปยัง Response...
องค์ประกอบของ Workflow มี 3 อย่าง...
Nodes... คือหน่วยทำงานแต่ละอัน...
Connections... คือเส้นเชื่อมระหว่าง Node...
และ Data... คือข้อมูลที่ไหลผ่านเป็น JSON ครับ...

มาดูประเภทของ Node กันครับ... แบ่งเป็น 3 ประเภท...
ประเภทแรก... Trigger Node... เป็นจุดเริ่มต้น Workflow...
ตัวอย่างเช่น Webhook, Schedule, Email Trigger...
ประเภทที่สอง... Action Node... ทำงานบางอย่าง...
ตัวอย่างเช่น HTTP Request, Send Email, Database...
ประเภทที่สาม... Logic Node... ควบคุม flow...
ตัวอย่างเช่น IF, Switch, Merge ครับ...

มาดู Data Flow ใน n8n กันครับ...
หลักการคือ... ข้อมูลไหลจาก Node หนึ่งไปยังอีก Node...
ข้อมูลอยู่ในรูปแบบ JSON...
และแต่ละ Node สามารถแก้ไข เพิ่ม หรือลบข้อมูลได้...
ตัวอย่างเช่น Node 1 มี JSON... ส่งต่อไป Node 2...
Node 2 ก็มี JSON ของตัวเอง... แล้วส่งต่อไป Node 3 ครับ...

มาดู JSON Data Structure ใน n8n กันครับ...
โครงสร้างข้อมูลจะเป็น Array ของ Items...
แต่ละ Item มี property ชื่อ json...
ข้างในมีข้อมูลต่างๆ เช่น name, age, scores...
หมายเหตุสำคัญคือ... n8n ส่งข้อมูลเป็น Array ของ Items เสมอครับ...
ต้องจำไว้นะครับ เพราะจะได้เข้าถึงข้อมูลได้ถูกต้อง...

มาดูวิธีเข้าถึงข้อมูลใน Code Node กันครับ...
ถ้าต้องการดึง item แรก... ใช้ $input.first().json...
ถ้าต้องการดึงทุก items... ใช้ $input.all()...
ถ้าต้องการเข้าถึง field... ใช้ item.name หรือ item.scores...
เหล่านี้เป็นวิธีพื้นฐานในการเข้าถึงข้อมูลครับ...

มาถึงหัวข้อที่สี่... Essential Nodes ครับ...
เริ่มที่ Webhook Node...
Webhook คือ การรับ HTTP Request จากภายนอก...
การตั้งค่าสำคัญมี...
HTTP Method... เลือก GET, POST, PUT, หรือ DELETE...
Path... กำหนด URL path เช่น /my-webhook...
Response Mode... เลือก Immediately หรือ Last Node...
URL ที่ได้จะมี 2 แบบ...
Test Mode ใช้ webhook-test...
Production Mode ใช้ webhook ครับ...

มาดู Code Node กันครับ...
Code Node คือ การเขียน JavaScript เพื่อประมวลผลข้อมูล...
โครงสร้างพื้นฐานคือ...
รับข้อมูล input ด้วย $input.first().json...
ประมวลผลตามที่ต้องการ...
แล้วส่งข้อมูล output ด้วย return...
return เป็น array ของ object ที่มี property json ครับ...

มาดู Tips สำหรับ Code Node กันครับ...
Tip ที่ 1... ดึงข้อมูลจาก body ของ Webhook...
ใช้ item.body หรือ item... เพื่อรองรับทั้ง 2 กรณี...
Tip ที่ 2... ประมวลผล Array...
ใช้ reduce function เพื่อหาผลรวม...
แล้วหารด้วย length เพื่อหาค่าเฉลี่ย...
Tip ที่ 3... เขียนเงื่อนไข...
ใช้ ternary operator เช่น avg >= 50 ? 'passed' : 'failed' ครับ...

มาดู HTTP Request Node กันครับ...
HTTP Request คือ การเรียก API ภายนอก...
การตั้งค่าประกอบด้วย...
Method... เลือก GET, POST, PUT, DELETE...
URL... ใส่ URL ของ API...
Headers... เช่น Content-Type, Authorization...
Body... ข้อมูลที่จะส่งสำหรับ POST หรือ PUT...
ตัวอย่างการใช้งานเช่น... ดึงข้อมูลจาก REST API...
ส่งข้อมูลไปยัง Server อื่น... หรือเรียกใช้ Third-party Services ครับ...

มาดู IF Node และ Switch Node กันครับ...
IF Node ใช้แยก flow เป็น 2 ทาง... True หรือ False...
เหมาะกับเงื่อนไขง่ายๆ...
ตัวอย่างเช่น ถ้า score มากกว่าหรือเท่ากับ 50 ไป passed...
ถ้าน้อยกว่า 50 ไป failed...
ส่วน Switch Node ใช้แยก flow เป็นหลายทาง...
เหมาะกับกรณีซับซ้อนที่มีหลายเงื่อนไข...
ตัวอย่างเช่น Grade A ไปทาง 1... Grade B ไปทาง 2... Grade F ไปทาง 3 ครับ...

มาถึงหัวข้อสุดท้าย... Hands-on Demo ครับ...
Demo ที่ 1... Hello World Workflow...
ขั้นตอนมีดังนี้...
สร้าง Workflow ใหม่...
เพิ่ม Manual Trigger Node...
เพิ่ม Code Node แล้วใส่โค้ด return message Hello World...
คลิก Test Workflow...
แล้วดูผลลัพธ์ครับ...

Demo ที่ 2... Student Grade Calculator...
Workflow ประกอบด้วย Webhook ต่อไปยัง Code แล้วต่อไปยัง Response...
ขั้นตอนมีดังนี้...
Webhook รับข้อมูลนักศึกษา...
Code Node คำนวณ total, average, grade, และ status...
แล้วส่ง JSON Response กลับไปครับ...

มาดูวิธี Export และ Import Workflow กันครับ...
การ Export Workflow...
คลิก Menu สามจุดมุมขวาบน...
เลือก Download...
บันทึกเป็นไฟล์ .json...
การ Import Workflow...
คลิก Import from File...
เลือกไฟล์ .json...
Workflow จะถูกโหลดเข้ามาครับ...

มาดู Lab 01 กันครับ... Student Grade Calculator...
งานที่ต้องทำมีดังนี้...
สร้าง Workflow รับข้อมูลนักศึกษา...
คำนวณ total และ average...
ตัดเกรด A B C D F...
กำหนด status passed หรือ failed...
Export เป็นไฟล์ workflow.json...
แล้ว Push ขึ้น GitHub...
คะแนนเต็ม 100 คะแนน ตรวจอัตโนมัติครับ...

มาสรุปสิ่งที่เรียนรู้ในวันนี้กันครับ...
หนึ่ง... Workflow Automation... ทำงานซ้ำๆ อัตโนมัติ...
สอง... n8n... Open Source, Self-hosted, Node-based...
สาม... Core Concepts... Workflow, Node, Connection, JSON...
สี่... Essential Nodes... Webhook, Code, HTTP Request, IF...
และห้า... Data Flow... JSON ไหลผ่าน Node ครับ...

มาถึงตอนจบแล้วครับ!...
มีคำถามอะไรไหมครับ?...
ถ้าไม่มีคำถาม... เราพักเบรกกันสักครู่...
แล้วก็มาทำ Lab 01 ด้วยกันครับ...
ขอบคุณที่ตั้งใจฟัง... สวัสดีครับ!
"""

# ============================================
# MAIN
# ============================================

async def main():
    print("=" * 60)
    print("🎙️ Audio Podcast Generator - Week 1: n8n Fundamental")
    print("=" * 60)
    print(f"🎤 Voice: {VOICE}")
    print(f"⏱️ Speed: {RATE}")
    print(f"🎧 Output: {OUTPUT_FILE}")
    print("=" * 60 + "\n")
    
    print("🎤 กำลังสร้างเสียง AI... (รอสักครู่)")
    
    # สร้างเสียงจาก script ทั้งหมดในครั้งเดียว
    communicate = edge_tts.Communicate(SCRIPT, VOICE, rate=RATE)
    await communicate.save(OUTPUT_FILE)
    
    # แสดงข้อมูลไฟล์
    if Path(OUTPUT_FILE).exists():
        size_mb = Path(OUTPUT_FILE).stat().st_size / (1024 * 1024)
        print(f"\n✅ สร้างเสียงเสร็จสมบูรณ์!")
        print(f"\n📊 ข้อมูลไฟล์เสียง:")
        print(f"   ไฟล์: {OUTPUT_FILE}")
        print(f"   ขนาด: {size_mb:.1f} MB")
    
    print("\n" + "=" * 60)
    print("🎉 เสร็จสิ้น! เปิดฟังได้เลยครับ")
    print("=" * 60)

if __name__ == "__main__":
    asyncio.run(main())
