"""
🎬 Video Generator - Week 1: n8n Fundamental
=============================================
สร้างวีดีโอบรรยายจาก PDF + Script พร้อมเสียง AI ภาษาไทย
เนื้อหาจาก lecture.tex (27 slides)

Setup:
    conda activate video-generator

Usage:
    python video_generator_lab01.py
"""

import asyncio
import edge_tts
from pathlib import Path
from pdf2image import convert_from_path
from moviepy.editor import ImageClip, AudioFileClip, concatenate_videoclips, CompositeAudioClip

# ============================================
# CONFIGURATION
# ============================================
PDF_FILE = "../Lecture/lecture.pdf"
OUTPUT_VIDEO = "week01-n8n-fundamental-lecture.mp4"

# เสียงไทย
VOICE = "th-TH-NiwatNeural"
# VOICE = "th-TH-PremwadeeNeural"  # เสียงผู้หญิง

# ลดความเร็วลง 15% เพื่อความชัดเจน
RATE = "-15%"

DPI = 200

# ============================================
# SCRIPTS - Week 1: n8n Fundamental
# อิงจาก lecture.tex (27 slides)
# ============================================
SCRIPTS = [
    # Slide 1 - Title Page
    """สวัสดีครับนักศึกษาทุกคน...
    ยินดีต้อนรับเข้าสู่ Week 1... เรื่อง n8n Fundamental ครับ...
    วันนี้เราจะมาเรียนรู้เกี่ยวกับ Introduction to Workflow Automation...
    และทำความรู้จักกับ n8n ซึ่งเป็นเครื่องมือที่เราจะใช้ตลอดคอร์สนี้...
    พร้อมกันหรือยังครับ?... ไปเริ่มกันเลย!""",
    
    # Slide 2 - สารบัญ
    """มาดูสารบัญกันก่อนนะครับ...
    วันนี้เราจะเรียน 5 หัวข้อหลักๆ...
    หัวข้อแรก... Introduction to Workflow Automation...
    หัวข้อที่สอง... n8n Overview...
    หัวข้อที่สาม... Core Concepts...
    หัวข้อที่สี่... Essential Nodes...
    และหัวข้อสุดท้าย... Hands-on Demo...
    พร้อมแล้วก็ไปกันเลยครับ!""",
    
    # Slide 3 - Workflow Automation คืออะไร?
    """มาเริ่มกันที่หัวข้อแรกครับ... Workflow Automation คืออะไร?...
    Workflow Automation คือ การทำให้งานที่ทำซ้ำๆ ทำงานอัตโนมัติ...
    ลองเปรียบเทียบดูนะครับ...
    ก่อน Automation... เราต้องทำงานซ้ำๆ ด้วยมือ... เสียเวลามาก...
    มีโอกาสผิดพลาดสูง... และต้องใช้คนตลอดเวลา...
    แต่หลัง Automation... ระบบทำงานอัตโนมัติ... ประหยัดเวลา...
    ลดข้อผิดพลาด... และทำงานได้ตลอด 24 ชั่วโมง 7 วันครับ""",
    
    # Slide 4 - ทำไมต้อง Automate?
    """ทำไมเราต้อง Automate ครับ?...
    มาดูประโยชน์ของ Workflow Automation กันนะครับ...
    หนึ่ง... ประหยัดเวลา... ลดงาน manual ที่ทำซ้ำๆ...
    สอง... ลดข้อผิดพลาด... ระบบทำงานตาม logic ที่กำหนด...
    สาม... เพิ่มประสิทธิภาพ... ทำงานได้เร็วขึ้น...
    สี่... Scalable... รองรับงานจำนวนมากได้...
    และห้า... ติดตามได้... มี log และ history ครับ""",
    
    # Slide 5 - ตัวอย่างการใช้งาน
    """มาดูตัวอย่างการใช้งาน Workflow Automation กันครับ...
    ในฝั่ง Business... เราสามารถใช้...
    ส่ง Email อัตโนมัติ... แจ้งเตือนใน Slack หรือ Line...
    สร้าง Report อัตโนมัติ... Sync ข้อมูลระหว่างระบบ...
    ส่วนในฝั่ง Development... เราใช้ได้กับ...
    CI/CD Pipeline... API Integration...
    Data Processing... และ Monitoring แอนด์ Alerting ครับ""",
    
    # Slide 6 - เปรียบเทียบ Tools
    """มาเปรียบเทียบ Workflow Automation Tools กันครับ...
    เรามี n8n, Zapier, และ Make...
    n8n เป็น Open Source... Self-hosted ได้...
    Free Tier ไม่จำกัด... และมี Code Node ที่ทรงพลัง...
    ส่วน Zapier และ Make ไม่ใช่ Open Source...
    ไม่สามารถ Self-hosted ได้... และ Free Tier มีข้อจำกัด...
    สรุปคือ n8n เท่ากับ Open Source บวก Self-hosted บวก Free บวก Powerful ครับ""",
    
    # Slide 7 - ทำไมเลือก n8n?
    """ทำไมเราถึงเลือก n8n ครับ?...
    หนึ่ง... Open Source... ฟรี และดู source code ได้...
    สอง... Self-hosted... ติดตั้งบน server ตัวเอง ควบคุมข้อมูลได้...
    สาม... No Vendor Lock-in... ไม่ผูกติดกับ provider...
    สี่... มากกว่า 400 Integrations... เชื่อมต่อได้หลายบริการ...
    ห้า... Code Node... เขียน JavaScript ได้เต็มที่...
    และหก... Active Community... มีคนใช้และพัฒนาต่อเนื่องครับ""",
    
    # Slide 8 - n8n คืออะไร?
    """มาถึงหัวข้อที่สอง... n8n Overview ครับ...
    n8n อ่านว่า โนดเมชัน หรือ nodemation...
    เป็น Workflow Automation Tool...
    สร้างโดย Jan Oberhauser ในปี 2019...
    เขียนด้วย TypeScript...
    License เป็นแบบ Fair-code หรือ Source Available...
    และมี GitHub Stars มากกว่า 40,000 ครับ...
    n8n ย่อมาจาก node-based automation ครับ""",
    
    # Slide 9 - สถาปัตยกรรมของ n8n
    """มาดูสถาปัตยกรรมของ n8n กันครับ...
    หลักการทำงานคือ... มี Trigger Node... ส่งข้อมูล JSON ไปยัง Process Node...
    แล้ว Process Node ก็ส่งต่อไปยัง Action Node...
    หลักการสำคัญคือ...
    Node-based... แต่ละ Node ทำหน้าที่เฉพาะ...
    Visual Editor... ลากวาง เชื่อมต่อ Node ได้ง่าย...
    และ Data Flow... ข้อมูลไหลผ่าน Node เป็น JSON ครับ""",
    
    # Slide 10 - การติดตั้ง n8n
    """มาดูวิธีติดตั้ง n8n กันครับ...
    วิธีที่ 1 ใช้ Docker ซึ่งเป็นวิธีที่แนะนำ...
    รันคำสั่ง docker run แล้วกำหนด port 5678...
    วิธีที่ 2 ใช้ npm...
    รันคำสั่ง npm install n8n -g...
    แล้วก็รัน n8n start...
    หลังจากติดตั้งเสร็จ เปิดใช้งานที่ URL localhost port 5678 ครับ""",
    
    # Slide 11 - n8n Interface
    """มาดู n8n Interface กันครับ...
    ส่วนประกอบหลักมี 5 ส่วน...
    หนึ่ง... Canvas... พื้นที่สร้าง Workflow อยู่ตรงกลาง...
    สอง... Node Panel... รายการ Node ทั้งหมดอยู่ทางซ้าย...
    สาม... Execution Panel... ดูผลการทำงานอยู่ทางขวา...
    สี่... Top Menu... มีปุ่ม Save, Execute, Settings...
    และห้า... Sidebar... มี Workflows, Credentials, Variables ครับ""",
    
    # Slide 12 - Workflow คืออะไร?
    """มาถึงหัวข้อที่สาม... Core Concepts ครับ...
    Workflow คืออะไร?...
    Workflow คือ ชุดของ Node ที่เชื่อมต่อกันเพื่อทำงานอัตโนมัติ...
    ตัวอย่างเช่น... Webhook Node ต่อไปยัง Code Node...
    แล้ว Code Node ก็ต่อไปยัง Response...
    องค์ประกอบของ Workflow มี 3 อย่าง...
    Nodes... คือหน่วยทำงานแต่ละอัน...
    Connections... คือเส้นเชื่อมระหว่าง Node...
    และ Data... คือข้อมูลที่ไหลผ่านเป็น JSON ครับ""",
    
    # Slide 13 - ประเภทของ Node
    """มาดูประเภทของ Node กันครับ... แบ่งเป็น 3 ประเภท...
    ประเภทแรก... Trigger Node... เป็นจุดเริ่มต้น Workflow...
    ตัวอย่างเช่น Webhook, Schedule, Email Trigger...
    ประเภทที่สอง... Action Node... ทำงานบางอย่าง...
    ตัวอย่างเช่น HTTP Request, Send Email, Database...
    ประเภทที่สาม... Logic Node... ควบคุม flow...
    ตัวอย่างเช่น IF, Switch, Merge ครับ""",
    
    # Slide 14 - Data Flow ใน n8n
    """มาดู Data Flow ใน n8n กันครับ...
    หลักการคือ... ข้อมูลไหลจาก Node หนึ่งไปยังอีก Node...
    ข้อมูลอยู่ในรูปแบบ JSON...
    และแต่ละ Node สามารถแก้ไข เพิ่ม หรือลบข้อมูลได้...
    ตัวอย่างเช่น Node 1 มี JSON... ส่งต่อไป Node 2...
    Node 2 ก็มี JSON ของตัวเอง... แล้วส่งต่อไป Node 3 ครับ""",
    
    # Slide 15 - JSON Data Structure
    """มาดู JSON Data Structure ใน n8n กันครับ...
    โครงสร้างข้อมูลจะเป็น Array ของ Items...
    แต่ละ Item มี property ชื่อ json...
    ข้างในมีข้อมูลต่างๆ เช่น name, age, scores...
    หมายเหตุสำคัญคือ... n8n ส่งข้อมูลเป็น Array ของ Items เสมอครับ...
    ต้องจำไว้นะครับ เพราะจะได้เข้าถึงข้อมูลได้ถูกต้อง""",
    
    # Slide 16 - การเข้าถึงข้อมูลใน Code Node
    """มาดูวิธีเข้าถึงข้อมูลใน Code Node กันครับ...
    ถ้าต้องการดึง item แรก... ใช้ $input.first().json...
    ถ้าต้องการดึงทุก items... ใช้ $input.all()...
    ถ้าต้องการเข้าถึง field... ใช้ item.name หรือ item.scores...
    เหล่านี้เป็นวิธีพื้นฐานในการเข้าถึงข้อมูลครับ""",
    
    # Slide 17 - Webhook Node
    """มาถึงหัวข้อที่สี่... Essential Nodes ครับ...
    เริ่มที่ Webhook Node...
    Webhook คือ การรับ HTTP Request จากภายนอก...
    การตั้งค่าสำคัญมี...
    HTTP Method... เลือก GET, POST, PUT, หรือ DELETE...
    Path... กำหนด URL path เช่น /my-webhook...
    Response Mode... เลือก Immediately หรือ Last Node...
    URL ที่ได้จะมี 2 แบบ...
    Test Mode ใช้ webhook-test...
    Production Mode ใช้ webhook ครับ""",
    
    # Slide 18 - Code Node
    """มาดู Code Node กันครับ...
    Code Node คือ การเขียน JavaScript เพื่อประมวลผลข้อมูล...
    โครงสร้างพื้นฐานคือ...
    รับข้อมูล input ด้วย $input.first().json...
    ประมวลผลตามที่ต้องการ...
    แล้วส่งข้อมูล output ด้วย return...
    return เป็น array ของ object ที่มี property json ครับ""",
    
    # Slide 19 - Code Node Tips
    """มาดู Tips สำหรับ Code Node กันครับ...
    Tip ที่ 1... ดึงข้อมูลจาก body ของ Webhook...
    ใช้ item.body หรือ item... เพื่อรองรับทั้ง 2 กรณี...
    Tip ที่ 2... ประมวลผล Array...
    ใช้ reduce function เพื่อหาผลรวม...
    แล้วหารด้วย length เพื่อหาค่าเฉลี่ย...
    Tip ที่ 3... เขียนเงื่อนไข...
    ใช้ ternary operator เช่น avg >= 50 ? 'passed' : 'failed' ครับ""",
    
    # Slide 20 - HTTP Request Node
    """มาดู HTTP Request Node กันครับ...
    HTTP Request คือ การเรียก API ภายนอก...
    การตั้งค่าประกอบด้วย...
    Method... เลือก GET, POST, PUT, DELETE...
    URL... ใส่ URL ของ API...
    Headers... เช่น Content-Type, Authorization...
    Body... ข้อมูลที่จะส่งสำหรับ POST หรือ PUT...
    ตัวอย่างการใช้งานเช่น... ดึงข้อมูลจาก REST API...
    ส่งข้อมูลไปยัง Server อื่น... หรือเรียกใช้ Third-party Services ครับ""",
    
    # Slide 21 - IF Node และ Switch Node
    """มาดู IF Node และ Switch Node กันครับ...
    IF Node ใช้แยก flow เป็น 2 ทาง... True หรือ False...
    เหมาะกับเงื่อนไขง่ายๆ...
    ตัวอย่างเช่น ถ้า score มากกว่าหรือเท่ากับ 50 ไป passed...
    ถ้าน้อยกว่า 50 ไป failed...
    ส่วน Switch Node ใช้แยก flow เป็นหลายทาง...
    เหมาะกับกรณีซับซ้อนที่มีหลายเงื่อนไข...
    ตัวอย่างเช่น Grade A ไปทาง 1... Grade B ไปทาง 2... Grade F ไปทาง 3 ครับ""",
    
    # Slide 22 - Demo Hello World
    """มาถึงหัวข้อสุดท้าย... Hands-on Demo ครับ...
    Demo ที่ 1... Hello World Workflow...
    ขั้นตอนมีดังนี้...
    สร้าง Workflow ใหม่...
    เพิ่ม Manual Trigger Node...
    เพิ่ม Code Node แล้วใส่โค้ด return message Hello World...
    คลิก Test Workflow...
    แล้วดูผลลัพธ์ครับ""",
    
    # Slide 23 - Demo Grade Calculator
    """Demo ที่ 2... Student Grade Calculator...
    Workflow ประกอบด้วย Webhook ต่อไปยัง Code แล้วต่อไปยัง Response...
    ขั้นตอนมีดังนี้...
    Webhook รับข้อมูลนักศึกษา...
    Code Node คำนวณ total, average, grade, และ status...
    แล้วส่ง JSON Response กลับไปครับ""",
    
    # Slide 24 - Export Import Workflow
    """มาดูวิธี Export และ Import Workflow กันครับ...
    การ Export Workflow...
    คลิก Menu สามจุดมุมขวาบน...
    เลือก Download...
    บันทึกเป็นไฟล์ .json...
    การ Import Workflow...
    คลิก Import from File...
    เลือกไฟล์ .json...
    Workflow จะถูกโหลดเข้ามาครับ""",
    
    # Slide 25 - Lab Preview
    """มาดู Lab 01 กันครับ... Student Grade Calculator...
    งานที่ต้องทำมีดังนี้...
    สร้าง Workflow รับข้อมูลนักศึกษา...
    คำนวณ total และ average...
    ตัดเกรด A B C D F...
    กำหนด status passed หรือ failed...
    Export เป็นไฟล์ workflow.json...
    แล้ว Push ขึ้น GitHub...
    คะแนนเต็ม 100 คะแนน ตรวจอัตโนมัติครับ""",
    
    # Slide 26 - สรุป
    """มาสรุปสิ่งที่เรียนรู้ในวันนี้กันครับ...
    หนึ่ง... Workflow Automation... ทำงานซ้ำๆ อัตโนมัติ...
    สอง... n8n... Open Source, Self-hosted, Node-based...
    สาม... Core Concepts... Workflow, Node, Connection, JSON...
    สี่... Essential Nodes... Webhook, Code, HTTP Request, IF...
    และห้า... Data Flow... JSON ไหลผ่าน Node ครับ""",
    
    # Slide 27 - Q&A
    """มาถึงตอนจบแล้วครับ!...
    มีคำถามอะไรไหมครับ?...
    ถ้าไม่มีคำถาม... เราพักเบรกกันสักครู่...
    แล้วก็มาทำ Lab 01 ด้วยกันครับ...
    ขอบคุณที่ตั้งใจฟัง... สวัสดีครับ!""",
]

# ============================================
# FUNCTIONS
# ============================================

async def generate_audio(text: str, output_file: str):
    """สร้างไฟล์เสียงจากข้อความ"""
    communicate = edge_tts.Communicate(text, VOICE, rate=RATE)
    await communicate.save(output_file)

async def generate_all_audio():
    """สร้างเสียงทุก slide"""
    audio_dir = Path("audio")
    audio_dir.mkdir(exist_ok=True)
    
    print("🎤 กำลังสร้างเสียง AI...")
    
    for i, script in enumerate(SCRIPTS, 1):
        output_file = audio_dir / f"slide_{i:02d}.mp3"
        await generate_audio(script, str(output_file))
        print(f"  ✅ Slide {i}/{len(SCRIPTS)}")
    
    print("✅ สร้างเสียงเสร็จสมบูรณ์!\n")

def convert_pdf_to_images():
    """แปลง PDF เป็นรูปภาพ"""
    images_dir = Path("images")
    images_dir.mkdir(exist_ok=True)
    
    print("🖼️ กำลังแปลง PDF เป็นรูปภาพ...")
    
    # ตรวจสอบว่ามีไฟล์ PDF หรือไม่
    if not Path(PDF_FILE).exists():
        print(f"❌ ไม่พบไฟล์ PDF: {PDF_FILE}")
        return 0
    
    images = convert_from_path(PDF_FILE, dpi=DPI)
    
    for i, image in enumerate(images, 1):
        output_file = images_dir / f"slide_{i:02d}.png"
        image.save(str(output_file), "PNG")
        print(f"  ✅ Slide {i}/{len(images)}")
    
    print("✅ แปลง PDF เสร็จสมบูรณ์!\n")
    return len(images)

def create_video(num_slides: int):
    """สร้างวีดีโอจากรูปภาพและเสียง"""
    print("🎬 กำลังสร้างวีดีโอ...")
    
    clips = []
    audio_clips = []  # เก็บ reference ของ audio clips
    total_duration = 0
    
    for i in range(1, num_slides + 1):
        image_file = f"images/slide_{i:02d}.png"
        audio_file = f"audio/slide_{i:02d}.mp3"
        
        if not Path(image_file).exists():
            print(f"  ⚠️ ไม่พบไฟล์รูป slide {i}")
            continue
            
        if not Path(audio_file).exists():
            print(f"  ⚠️ ไม่พบไฟล์เสียง slide {i}, ใช้เวลา 5 วินาที")
            duration = 5
            clip = ImageClip(image_file).set_duration(duration)
        else:
            audio = AudioFileClip(audio_file)
            audio_clips.append(audio)  # เก็บ reference
            duration = audio.duration
            clip = ImageClip(image_file).set_duration(duration).set_audio(audio)
        
        clips.append(clip)
        total_duration += duration
        print(f"  ✅ Slide {i}/{num_slides} ({duration:.1f}s)")
    
    print(f"\n📊 ความยาวรวม: {total_duration/60:.1f} นาที")
    
    # รวม clips ทั้งหมด
    print("\n📼 กำลังรวมวีดีโอ...")
    final_video = concatenate_videoclips(clips, method="compose")
    
    # Export with audio
    print("💾 กำลัง export วีดีโอ...")
    final_video.write_videofile(
        OUTPUT_VIDEO,
        fps=24,
        codec="libx264",
        audio_codec="aac",
        audio_bitrate="192k",
        threads=4,
        preset="medium",
    )
    
    # Cleanup
    final_video.close()
    for clip in clips:
        clip.close()
    for audio in audio_clips:
        audio.close()
    
    print(f"\n✅ สร้างวีดีโอเสร็จสมบูรณ์: {OUTPUT_VIDEO}")

def get_video_info():
    """แสดงข้อมูลวีดีโอ"""
    if Path(OUTPUT_VIDEO).exists():
        size_mb = Path(OUTPUT_VIDEO).stat().st_size / (1024 * 1024)
        print(f"\n📊 ข้อมูลวีดีโอ:")
        print(f"   ไฟล์: {OUTPUT_VIDEO}")
        print(f"   ขนาด: {size_mb:.1f} MB")

# ============================================
# MAIN
# ============================================

async def main():
    print("=" * 60)
    print("🎬 Video Generator - Week 1: n8n Fundamental")
    print("=" * 60)
    print(f"📄 PDF: {PDF_FILE}")
    print(f"🎤 Voice: {VOICE}")
    print(f"⏱️ Speed: {RATE}")
    print(f"📹 Output: {OUTPUT_VIDEO}")
    print(f"📝 Slides: {len(SCRIPTS)}")
    print("=" * 60 + "\n")
    
    # Check PDF exists
    if not Path(PDF_FILE).exists():
        print(f"❌ ไม่พบไฟล์ PDF: {PDF_FILE}")
        print("   กรุณาตรวจสอบว่ามีไฟล์ lecture.pdf ในโฟลเดอร์ Lecture/")
        print("   หรือ compile lecture.tex เป็น PDF ก่อน")
        return
    
    # Step 1: Generate audio
    await generate_all_audio()
    
    # Step 2: Convert PDF to images
    num_slides = convert_pdf_to_images()
    
    if num_slides == 0:
        print("❌ ไม่สามารถแปลง PDF ได้")
        return
    
    # Check script count matches slides
    if num_slides != len(SCRIPTS):
        print(f"⚠️ Warning: PDF มี {num_slides} slides แต่ script มี {len(SCRIPTS)} ข้อความ")
    
    # Step 3: Create video
    create_video(min(num_slides, len(SCRIPTS)))
    
    # Show info
    get_video_info()
    
    print("\n" + "=" * 60)
    print("🎉 เสร็จสิ้น! เปิดไฟล์ดูได้เลยครับ")
    print("=" * 60)

if __name__ == "__main__":
    asyncio.run(main())
